spring:
  application:
    name: registry-service
  profiles:
    active: native
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    renewal-percent-threshold: 0.85
server:
  port: 8761
