
spring:
  application:
    name: product-service
  cloud:
    config:
      name: product-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        failure-rate-threshold: 50
        slow-call-duration-threshold: 500ms
        sliding-window-size: 10
        minimum-number-of-calls: 5
        sliding-window-type: COUNT_BASED
        wait-duration-in-open-state: 5s
        slow-call-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 3
    instances:
      catalog-app:
        baseConfig: default
      inventory-app:
        baseConfig: default
  retry:
    configs:
      default:
        max-attempts: 5
        wait-duration: 100
        retry-exceptions:
          - java.io.IOException
          - feign.FeignException.FeignServerException
          - org.springframework.web.client.HttpServerErrorException
    instances:
      catalog-app:
        base-config: default
      inventory-app:
        base-config: default
#server:
#  port: 8083
